# Generated by Django 5.0.6 on 2024-06-01 14:03

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='books')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isDelete', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
    ]
