# Generated by Django 5.0.6 on 2024-06-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=50)),
                ('picture', models.ImageField(default='', upload_to='books')),
                ('number', models.CharField(default='1', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.booksinfo')),
            ],
        ),
    ]
